### PR TITLE
Added support for dynamic versioning; added gitignore for bin directory.

### PR DESCRIPTION
**Pull request by bweir**
Hey David, here's support for dynamic versioning. As soon as you create your first git tag, the version number will start reflecting the last tag made. Read up on Git tagging here:

http://git-scm.com/book/en/v2/Git-Basics-Tagging

GitHub recommends semantic versioning for release numbers, i.e. major.minor.patch release, so the null release follows that pattern. I've already found the patch release number useful for when I released 0.25.1, so I thought you'd like to try it out.

Anyway, lemme know if you have any problems!

### CODE REVIEW

**Comment by dbetz** [comment]
Umm… I’m not sure if my tag worked or not. I think it only got created in my local repository. How do I list the tags that are present on github?

**Comment by bweir** [comment]
Ahh, when you do a git push, you need to explicitly push tags with

```
 git push --tags
```

Then you can see the "1 release" on the top of the main repository page: https://github.com/dbetz/p1load

It looks like you did add a revision.
https://github.com/dbetz/p1load/releases

**Comment by dbetz** [comment]
Yeah, I figured it out after I send you the question. I didn’t do it quite that way though. I think I type something like

git push origin v0.1

**Comment by bweir** [comment]
That works but it only sends the one tag, so if for whatever reason you had
made multIple releases before uploading, they wouldn't have all come with.

**Comment by dbetz** [comment]
I wish I knew why Peter Jakacki was having trouble with p1load.

**Comment by bweir** [comment]
Haha, yeah, but without the environment that he has, there isn't much you
can do. I'm not even sure where to get my hands on a board that uses that
chipset.

**Pull request merged**
